spring:
  application:
    name: stock
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/stock_example?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
